import type { MiniSpill } from '../types/stresspause.types';
import { ArkivTetris } from './ArkivTetris';
import { InnboksNull } from './InnboksNull';
import { Kaffehelling } from './Kaffehelling';
import { KnusSkriveren } from './KnusSkriveren';
import { Papirball } from './Papirball';
import { RyddPulten } from './RyddPulten';
import { StifteAsmr } from './StifteAsmr';
import { Stressballen } from './Stressballen';

/** Legg til et nytt mini-spill her, så dukker det opp i menyen. */
export const MINI_SPILL: MiniSpill[] = [
  {
    id: 'kaffehelling',
    navn: 'Kaffepause',
    emoji: '☕',
    beskrivelse: 'Hell kaffen nøyaktig opp til streken. Jo bedre helling, jo mer energi.',
    kontroller: 'Hold inne og slipp',
    slikSpiller: 'Hold inne for å helle, og slipp når kaffen når streken.',
    navnEn: 'Coffee break',
    beskrivelseEn: 'Pour the coffee exactly up to the line. The better the pour, the more energy.',
    kontrollerEn: 'Hold and release',
    slikSpillerEn: 'Hold to pour, and let go when the coffee reaches the line.',
    Komponent: Kaffehelling,
    anledning: 'kaffepause',
  },
  {
    id: 'rydd-pulten',
    navn: 'Rydd pulten',
    emoji: '🧹',
    beskrivelse: 'Kald kaffe, post-its og en skademelding under bananskallet. Sorter rotet.',
    kontroller: 'Dra og slipp',
    slikSpiller: 'Dra hver ting til riktig kurv.',
    navnEn: 'Clean the desk',
    beskrivelseEn: 'Cold coffee, post-its and a claim report under the banana peel. Sort the mess.',
    kontrollerEn: 'Drag and drop',
    slikSpillerEn: 'Drag each item to the right basket.',
    Komponent: RyddPulten,
  },
  {
    id: 'stifte-asmr',
    navn: 'Stifte-ASMR',
    emoji: '📎',
    beskrivelse: 'Guitar Hero, men med stiftemaskin. Treff takten, hør den deilige ka-chunken.',
    kontroller: 'Mellomrom',
    slikSpiller: 'Trykk mellomrom når arket treffer streken.',
    navnEn: 'Stapler ASMR',
    beskrivelseEn: 'Guitar Hero, but with a stapler. Hit the beat, hear the glorious ka-chunk.',
    kontrollerEn: 'Space bar',
    slikSpillerEn: 'Press space when the sheet hits the line.',
    Komponent: StifteAsmr,
  },
  {
    id: 'innboks-null',
    navn: 'Innboks null',
    emoji: '📧',
    beskrivelse: 'Sveip e-poster til arkiv eller søppel. Møteinvitasjoner er alltid søppel.',
    kontroller: 'Sveip / piltaster',
    slikSpiller: 'Sveip jobb-e-post til arkiv og tull til søppel.',
    navnEn: 'Inbox zero',
    beskrivelseEn: 'Swipe emails to archive or trash. Meeting invites are always trash.',
    kontrollerEn: 'Swipe / arrow keys',
    slikSpillerEn: 'Swipe work emails to archive and nonsense to trash.',
    Komponent: InnboksNull,
  },
  {
    id: 'knus-skriveren',
    navn: 'Knus skriveren',
    emoji: '🖨️',
    beskrivelse: 'Den har hatt papirstopp siden 2019. Nå er det din tur.',
    kontroller: 'Klikk som en gal',
    slikSpiller: 'Klikk på skriveren så fort du kan.',
    navnEn: 'Smash the printer',
    beskrivelseEn: 'It has had a paper jam since 2019. Now it\'s your turn.',
    kontrollerEn: 'Click like mad',
    slikSpillerEn: 'Click the printer as fast as you can.',
    Komponent: KnusSkriveren,
  },
  {
    id: 'stressballen',
    navn: 'Stressballen',
    emoji: '🔴',
    beskrivelse: 'Klem og slipp i takt. Ballen dømmer deg ikke. Det gjør Bjarne.',
    kontroller: 'Hold inne',
    slikSpiller: 'Hold inne på KLEM, slipp på SLIPP.',
    navnEn: 'The stress ball',
    beskrivelseEn: 'Squeeze and release to the beat. The ball doesn\'t judge you. Bjarne does.',
    kontrollerEn: 'Hold down',
    slikSpillerEn: 'Hold on SQUEEZE, let go on RELEASE.',
    Komponent: Stressballen,
  },
  {
    id: 'papirball',
    navn: 'Papirball',
    emoji: '🧻',
    beskrivelse: 'Kast papirballer i søppelbøtta. Den står et nytt sted hver gang, men den er stor.',
    kontroller: 'Dra og slipp',
    slikSpiller: 'Dra bakover og slipp for å kaste i bøtta.',
    navnEn: 'Paper ball',
    beskrivelseEn: 'Throw paper balls in the bin. It moves every time, but it\'s big.',
    kontrollerEn: 'Drag and drop',
    slikSpillerEn: 'Pull back and let go to throw it in the bin.',
    Komponent: Papirball,
  },
  {
    id: 'arkiv-tetris',
    navn: 'Arkiv-tetris',
    emoji: '🗂️',
    beskrivelse: 'Stable skademapper i arkivet. Fullt arkiv? Bjarne makulerer alt. Du kan ikke tape.',
    kontroller: 'Piltaster',
    slikSpiller: 'Piltaster flytter og roterer, og fulle rader forsvinner.',
    navnEn: 'Archive Tetris',
    beskrivelseEn: 'Stack claim folders in the archive. Archive full? Bjarne shreds everything. You can\'t lose.',
    kontrollerEn: 'Arrow keys',
    slikSpillerEn: 'Arrow keys move and rotate, and full rows disappear.',
    Komponent: ArkivTetris,
  },
];
